mode:
  dev: true
server:
  port: 8090
db:
  dsn: go-parrot:password@tcp(127.0.0.1:3306)/go-parro?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 10 # 最多空闲连接数
  maxOpenConn: 10 # 最多打开连接数
log:
  MaxSize: 1
  MaxBackups: 10
  MaxAge: 90




