definitions:
  dto.BasicIdDTO:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  dto.UserAddDTO:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      real_name:
        type: string
    required:
    - name
    - password
    type: object
  dto.UserLoginDTO:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
info:
  contact:
    email: zhangzhouou@gmail.com
    name: Supuwoerc
    url: https://github.com/supuwoerc
  description: 鹦鹉学舌
  title: Go-Parrot
  version: 1.0.0
paths:
  /api/public/user/add:
    post:
      consumes:
      - application/json
      description: 用于根据ID查询用户
      parameters:
      - description: GET USER INFO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.BasicIdDTO'
      responses:
        "200":
          description: 操作成功
          schema:
            type: string
        "500":
          description: 操作失败
          schema:
            type: string
      summary: 查询用户
      tags:
      - 用户管理模块
  /api/public/user/login:
    post:
      consumes:
      - application/json
      description: 用于用户登录系统
      parameters:
      - description: User Login Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginDTO'
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
        "500":
          description: 登录失败
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户管理模块
swagger: "2.0"
