info:
  contact: {}
  description: 使用golang开发后台管理系统
  title: Go-Parrot鹦鹉学舌
  version: 1.0.0
paths:
  /api/v1/public/user/login:
    post:
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 登录成功
          schema:
            type: string
        "400":
          description: 登录失败
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户管理
swagger: "2.0"
