definitions:
  dto.BasicIdDTO:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  dto.UserAddDTO:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      real_name:
        type: string
    required:
    - name
    - password
    type: object
  dto.UserListDTO:
    properties:
      name:
        type: string
      page:
        type: integer
      page_size:
        type: integer
    type: object
  dto.UserLoginDTO:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  dto.UserUpdateDTO:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phone:
        type: string
      real_name:
        type: string
    required:
    - id
    type: object
  serializer.BasicResponse-any:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: zhangzhouou@gmail.com
    name: Supuwoerc
    url: https://github.com/supuwoerc
  description: 鹦鹉学舌
  title: Go-Parrot
  version: 1.0.0
paths:
  /api/public/npm/downloads:
    get:
      description: 根据指定的时间范围和包名获取下载数据
      parameters:
      - description: 包名
        in: query
        name: package
        required: true
        type: string
      - description: 开始日期 (默认为7天前)
        format: yyyy-mm-dd
        in: query
        name: start
        type: string
      - description: 结束日期 (默认为今天)
        format: yyyy-mm-dd
        in: query
        name: end
        type: string
      responses:
        "200":
          description: 成功返回数据
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 获取指定时间范围内的下载数据
      tags:
      - NPM数据查询
  /api/public/npm/info:
    get:
      description: 获取包meta信息
      parameters:
      - description: 包名
        in: query
        name: package
        required: true
        type: string
      responses:
        "200":
          description: 成功返回数据
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 获取包meta信息
      tags:
      - NPM数据查询
  /api/public/user/add:
    post:
      consumes:
      - application/json
      description: 用于添加用户
      parameters:
      - description: ADD USER INFO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserAddDTO'
      responses:
        "200":
          description: Successfully add
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 添加用户
      tags:
      - 用户管理模块
  /api/public/user/list:
    post:
      consumes:
      - application/json
      description: 查询用户列表
      parameters:
      - description: GET USER LIST
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserListDTO'
      responses:
        "200":
          description: Successfully get user list
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 查询用户列表
      tags:
      - 用户管理模块
  /api/public/user/login:
    post:
      consumes:
      - application/json
      description: 用于用户登录系统
      parameters:
      - description: User Login Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginDTO'
      responses:
        "200":
          description: Successfully login
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 用户登录
      tags:
      - 用户管理模块
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: 用于根据ID查询用户
      parameters:
      - description: GET USER INFO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.BasicIdDTO'
      responses:
        "200":
          description: Successfully get user info
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 查询用户
      tags:
      - 用户管理模块
  /api/user/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 根据用户ID删除用户
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 删除用户
      tags:
      - 用户管理模块
  /api/user/update:
    patch:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: Update User Info
        in: body
        name: userUpdateDTO
        required: true
        schema:
          $ref: '#/definitions/dto.UserUpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/serializer.BasicResponse-any'
      summary: 更新用户信息
      tags:
      - 用户管理模块
swagger: "2.0"
